feat: Upgrade to latest Docker image versions
SRM: v2023.8.4
MariaDB: v1.25.0
Tool Orchestration: v1.27.0
Workflow: v2.17.0

- helm hook requests internal key
- removed unused migration script parameters

diff --git a/chart/templates/internal-svc-job.yaml b/chart/templates/internal-svc-job.yaml
--- a/chart/templates/internal-svc-job.yaml
+++ b/chart/templates/internal-svc-job.yaml
@@ -47,8 +47,8 @@ spec:
 
             NAME='scan-service-srm-api-key'
             ID_PATTERN="\"id\":([0-9]*),\"name\":\"$NAME\""
-            KEYRESPONSE=$(curl -f -H "Authorization: Basic $ADMINCRED" {{ include "srm-web.serviceurl" . }}/x/admin/users/key)
-            if [ 0 -ne $? ]; then echo 'Failed to make request to "{{ include "srm-web.serviceurl" . }}/x/admin/users/key" - does your admin K8s secret "{{ include "srm-web.web.secret" . }}" have the correct password?'; exit 1; fi
+            KEYRESPONSE=$(curl -f -H "Authorization: Basic $ADMINCRED" {{ include "srm-web.serviceurl" . }}/x/admin/users/key?includeInternal=1)
+            if [ 0 -ne $? ]; then echo 'Failed to make request to "{{ include "srm-web.serviceurl" . }}/x/admin/users/key?includeInternal=1" - does your admin K8s secret "{{ include "srm-web.web.secret" . }}" have the correct password?'; exit 1; fi
 
             if [[ $KEYRESPONSE =~ $ID_PATTERN ]]
             then
